spring:
  jmx:
    enabled: false
  # --- Database Configuration (PostgreSQL) ---
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/findex

  # --- JPA (Hibernate) Configuration ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# --- Logging Configuration ---
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# --- API KEY ---
api:
  key: ${OPEN_API_KEY}
  url: ${OPEN_API_URL}